---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: petal-homework
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/petal-homework
      sourceRef:
        kind: GitRepository
        name: petal-homework
        namespace: flux-system
      interval: 1m
  interval: 5m0s

