---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: petal-homework
  namespace: flux-system
spec:
  interval: 1m 
  ref:
    branch: main
  url: https://github.com/Bearlock/petal-homework.git
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/

